# Generated by Django 4.2.6 on 2023-10-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AddField(
            model_name='post',
            name='Images',
            field=models.ImageField(default=1, upload_to='imgs'),
            preserve_default=False,
        ),
    ]
